# Generated by Django 6.0.2 on 2026-02-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('valvulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('proximamente_vencer', 'Próximamente a Vencer'), ('vencido', 'Vencido'), ('no_realizado', 'No Realizado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_servicio', to='valvulas.valvula')),
            ],
            options={
                'verbose_name': 'Alerta de Servicio',
                'verbose_name_plural': 'Alertas de Servicio',
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('calibracion', 'Calibración'), ('reparacion', 'Reparación'), ('otro', 'Otro')], max_length=50)),
                ('fecha_servicio', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='completado', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(limit_choices_to={'rol': 'comercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to='usuarios.perfilusuario')),
                ('valvula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='valvulas.valvula')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_servicio'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_certificado', models.CharField(choices=[('calibracion', 'Calibración'), ('mantenimiento', 'Mantenimiento')], max_length=50)),
                ('archivo_pdf', models.FileField(upload_to='certificados/%Y/%m/%d/')),
                ('numero_certificado', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('presion_inicial', models.CharField(blank=True, max_length=50)),
                ('presion_final', models.CharField(blank=True, max_length=50)),
                ('temperatura', models.CharField(blank=True, max_length=50)),
                ('resultado', models.CharField(blank=True, max_length=50)),
                ('notas_calibracion', models.TextField(blank=True)),
                ('laboratorio', models.CharField(blank=True, max_length=255)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=255)),
                ('extraido_exitosamente', models.BooleanField(default=False, help_text='Indica si los datos fueron extraídos exitosamente del PDF')),
                ('fecha_extraccion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
