# Generated by Django 6.0.2 on 2026-02-13 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='fecha_extraccion',
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_extraccion_datos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='usuario_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='servicios.servicio'),
        ),
    ]
