# Generated by Django 6.0.2 on 2026-02-16 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_certificado_fecha_extraccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Certificado (Legado)', 'verbose_name_plural': 'Certificados (Legado)'},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='extraido_exitosamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_legacy', to='servicios.servicio'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('calibracion', 'Certificado de Calibración'), ('mantenimiento', 'Informe de Mantenimiento'), ('reparacion', 'Informe de Reparación'), ('otro', 'Otro')], max_length=50)),
                ('archivo_pdf', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('nombre_original', models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255)),
                ('numero_documento', models.CharField(blank=True, db_index=True, max_length=100)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tecnico_responsable', models.CharField(blank=True, max_length=255)),
                ('presion_inicial', models.CharField(blank=True, max_length=50)),
                ('presion_final', models.CharField(blank=True, max_length=50)),
                ('temperatura', models.CharField(blank=True, max_length=50)),
                ('unidad_presion', models.CharField(blank=True, max_length=20)),
                ('resultado_calibracion', models.CharField(blank=True, max_length=50)),
                ('laboratorio', models.CharField(blank=True, max_length=255)),
                ('tipo_mantenimiento', models.CharField(blank=True, max_length=100)),
                ('descripcion_trabajos', models.TextField(blank=True)),
                ('estado_valvula', models.CharField(blank=True, max_length=100)),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('duracion_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('extraido_exitosamente', models.BooleanField(default=False)),
                ('error_extraccion', models.TextField(blank=True, help_text='Descripción del error si falló la extracción')),
                ('fecha_extraccion_datos', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servicios.servicio')),
                ('usuario_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_documento', '-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo_documento', 'servicio'], name='servicios_d_tipo_do_64a296_idx'), models.Index(fields=['numero_documento'], name='servicios_d_numero__588da0_idx')],
            },
        ),
    ]
