# Generated by Django 6.0.2 on 2026-02-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_certificado_options_and_more'),
        ('valvulas', '0002_valvula_norma_aplicable_valvula_presion_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='valvula',
            field=models.ForeignKey(blank=True, help_text='Referencia directa a la válvula para hoja de vida', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='valvulas.valvula'),
        ),
    ]
