# Generated by Django 6.0.2 on 2026-02-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_documento_valvula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion_trabajos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='error_extraccion',
            field=models.TextField(blank=True, help_text='Descripción del error si falló la extracción', null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado_valvula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='materiales_utilizados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='numero_documento',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='presion_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='presion_inicial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resultado_calibracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tecnico_responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_mantenimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='unidad_presion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
