# Generated by Django 6.0.2 on 2026-02-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_documento_descripcion_trabajos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio asociado (opcional si se vincula directamente a válvula)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servicios.servicio'),
        ),
    ]
