# Generated by Django 6.0.2 on 2026-02-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valvula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('codigo_interno', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(choices=[('alivio', 'Válvula de Alivio'), ('check', 'Válvula Check'), ('bola', 'Válvula de Bola'), ('aguja', 'Válvula de Aguja'), ('compuerta', 'Válvula de Compuerta'), ('otra', 'Otra')], max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=50)),
                ('presion_nominal', models.CharField(max_length=50, verbose_name='Presión Nominal')),
                ('temperatura_nominal', models.CharField(blank=True, max_length=50, verbose_name='Temperatura Nominal')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(help_text='Ubicación física de la válvula', max_length=255)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('descartada', 'Descartada')], default='activa', max_length=50)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_servicio', models.DateField(blank=True, null=True, verbose_name='Fecha Último Servicio')),
                ('fecha_ultima_calibracion', models.DateField(blank=True, null=True, verbose_name='Fecha Última Calibración')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valvulas', to='clientes.empresa')),
            ],
            options={
                'verbose_name': 'Válvula',
                'verbose_name_plural': 'Válvulas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_maxima_trabajo', models.CharField(blank=True, max_length=50)),
                ('capacidad_flujo', models.CharField(blank=True, max_length=100)),
                ('conexion_entrada', models.CharField(blank=True, max_length=100)),
                ('conexion_salida', models.CharField(blank=True, max_length=100)),
                ('rango_temperatura', models.CharField(blank=True, max_length=100)),
                ('certificacion', models.CharField(blank=True, max_length=255)),
                ('notas_tecnicas', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('valvula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='valvulas.valvula')),
            ],
            options={
                'verbose_name': 'Especificación Técnica',
                'verbose_name_plural': 'Especificaciones Técnicas',
            },
        ),
    ]
