# Generated by Django 6.0.2 on 2026-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valvulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvula',
            name='norma_aplicable',
            field=models.CharField(blank=True, help_text='ASME I, ASME VIII, etc', max_length=50),
        ),
        migrations.AddField(
            model_name='valvula',
            name='presion_set',
            field=models.CharField(blank=True, help_text='Para válvulas de seguridad', max_length=50, verbose_name='Presión SET'),
        ),
        migrations.AddField(
            model_name='valvula',
            name='tag_localizacion',
            field=models.CharField(blank=True, help_text='TAG o identificador de ubicación', max_length=100),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='fecha_ultimo_servicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Servicio/Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='numero_serie',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='presion_nominal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Presión Nominal'),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='tipo',
            field=models.CharField(choices=[('alivio', 'Válvula de Alivio/Seguridad'), ('control', 'Válvula de Control/Corte'), ('check', 'Válvula Check'), ('bola', 'Válvula de Bola'), ('aguja', 'Válvula de Aguja'), ('compuerta', 'Válvula de Compuerta'), ('otra', 'Otra')], max_length=100),
        ),
        migrations.AlterField(
            model_name='valvula',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física de la válvula', max_length=255),
        ),
    ]
