# Generated by Django 6.0.2 on 2026-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='zona_horaria',
            field=models.CharField(choices=[('UTC', 'UTC (Tiempo Universal)'), ('America/Bogota', 'Colombia (UTC-5)'), ('America/Guatemala', 'Guatemala (UTC-6)'), ('America/Mexico_City', 'México (UTC-6)'), ('America/Costa_Rica', 'Costa Rica (UTC-6)'), ('America/Panama', 'Panamá (UTC-5)'), ('America/Caracas', 'Venezuela (UTC-4)'), ('America/Lima', 'Perú (UTC-5)'), ('America/Argentina/Buenos_Aires', 'Argentina (UTC-3)'), ('America/Santiago', 'Chile (UTC-3)'), ('America/Sao_Paulo', 'Brasil (UTC-3)'), ('America/New_York', 'USA Este (UTC-5/-4)'), ('America/Chicago', 'USA Centro (UTC-6/-5)'), ('America/Denver', 'USA Montaña (UTC-7/-6)'), ('America/Los_Angeles', 'USA Oeste (UTC-8/-7)'), ('Europe/Madrid', 'España (UTC+1/+2)'), ('Europe/London', 'Reino Unido (UTC+0/+1)'), ('Europe/Paris', 'Francia (UTC+1/+2)'), ('Europe/Berlin', 'Alemania (UTC+1/+2)'), ('Asia/Dubai', 'Emiratos (UTC+4)'), ('Asia/Bangkok', 'Tailandia (UTC+7)'), ('Asia/Shanghai', 'China (UTC+8)'), ('Asia/Tokyo', 'Japón (UTC+9)'), ('Asia/Kolkata', 'India (UTC+5:30)'), ('Australia/Sydney', 'Australia (UTC+10/+11)')], default='America/Bogota', help_text='Zona horaria del usuario para mostrar fechas y horas', max_length=50),
        ),
    ]
